import generationConfigRaw from '../../scripts/openapi-generation.config.mjs?raw'
import generationScriptRaw from '../../scripts/generate-api-types.mjs?raw'
import gitAttributesRaw from '../../.gitattributes?raw'
import eslintConfigRaw from '../../eslint.config.js?raw'
import generatedApiRaw from '@/shared/types/generated/eiams-v1.ts?raw'
import packageJsonRaw from '../../package.json?raw'
import prettierIgnoreRaw from '../../.prettierignore?raw'
import provenanceRaw from '../../contracts/openapi/eiams-v1.provenance.json?raw'
import readmeRaw from '../../README.md?raw'
import { describe, expect, it } from 'vitest'

type PackageManifest = {
  scripts?: Record<string, string>
  devDependencies?: Record<string, string>
}

type OpenApiProvenance = {
  contractId: string
  contractVersion: string
  snapshotPath: string
  sha256: string
  coverage: {
    paths: number
    operations: number
    schemas: number
  }
}

const packageManifest = JSON.parse(packageJsonRaw) as PackageManifest
const provenance = JSON.parse(provenanceRaw) as OpenApiProvenance

describe('OpenAPI generation configuration', () => {
  it('pins the admitted contract input and generated type output path', () => {
    expect(provenance.contractId).toBe('eiams-v1')
    expect(provenance.snapshotPath).toBe('contracts/openapi/eiams-v1.openapi.json')
    expect(provenance.sha256).toMatch(/^[a-f0-9]{64}$/)
    expect(provenance.coverage).toEqual({ paths: 80, operations: 116, schemas: 156 })

    expect(generationConfigRaw).toContain("contractId: 'eiams-v1'")
    expect(generationConfigRaw).toContain("snapshotPath: 'contracts/openapi/eiams-v1.openapi.json'")
    expect(generationConfigRaw).toContain(
      "provenancePath: 'contracts/openapi/eiams-v1.provenance.json'",
    )
    expect(generationConfigRaw).toContain("outputPath: 'src/shared/types/generated/eiams-v1.ts'")
  })

  it('uses deterministic type-only openapi-typescript options', () => {
    expect(packageManifest.devDependencies?.['openapi-typescript']).toBe('7.13.0')
    expect(generationConfigRaw).toContain("openapiTypescriptVersion: '7.13.0'")
    expect(generationConfigRaw).toContain("'--export-type'")
    expect(generationConfigRaw).toContain("'--immutable'")
    expect(generationConfigRaw).toContain("'--alphabetize'")
    expect(generationConfigRaw).toContain("'--root-types'")
    expect(generationConfigRaw).toContain("'--root-types-no-schema-prefix'")
    expect(generationConfigRaw).not.toContain("'--path-params-as-types'")
    expect(generationConfigRaw).not.toContain("'--enum'")
    expect(generationConfigRaw).not.toContain("'--enum-values'")
  })

  it('exposes generation scripts and protects quality with generated-type drift checking', () => {
    expect(packageManifest.scripts?.['api:types:generate']).toBe(
      'node scripts/generate-api-types.mjs',
    )
    expect(packageManifest.scripts?.['api:types:check']).toBe(
      'node scripts/generate-api-types.mjs --check',
    )
    expect(packageManifest.scripts?.['api:types:dry']).toBe(
      'node scripts/generate-api-types.mjs --dry-run',
    )
    expect(packageManifest.scripts?.['quality']).toContain('pnpm run api:types:check')

    expect(readmeRaw).toContain('pnpm run api:types:dry')
    expect(readmeRaw).toContain('pnpm run api:types:generate')
    expect(readmeRaw).toContain('Generated API files must not be edited by hand')
  })

  it('commits the generated EIAMS v1 type surface from the admitted snapshot', () => {
    expect(generatedApiRaw).toContain('This file was auto-generated by openapi-typescript')
    expect(generatedApiRaw).toContain('export type paths =')
    expect(generatedApiRaw).toContain('export type components =')
    expect(generatedApiRaw).toContain('export interface operations')
    expect(generatedApiRaw).toContain(
      "export type DocumentStatus = components['schemas']['DocumentStatus'];",
    )
    expect(generatedApiRaw).toContain(
      'readonly DocumentStatus: "Draft" | "Submitted" | "Posted" | "Reversed" | "Cancelled" | "Rejected";',
    )
    expect(generatedApiRaw).toContain('readonly ProblemDetails:')
    expect(generatedApiRaw).toContain('readonly PositiveDecimal18_6: string;')
    expect(generatedApiRaw).toContain(
      'readonly factor: components["schemas"]["PositiveDecimal18_6"];',
    )
    expect(generatedApiRaw).toContain(
      'readonly conversionFactor: components["schemas"]["PositiveDecimal18_6"];',
    )
    expect(generatedApiRaw.split('\n').length).toBeGreaterThan(5_000)
  })

  it('keeps generated files out of lint and format rewrites', () => {
    expect(eslintConfigRaw).toContain("'src/shared/types/generated'")
    expect(prettierIgnoreRaw).toContain('src/shared/types/generated')
  })

  it('guards against stale provenance before writing generated types', () => {
    expect(generationScriptRaw).toContain('const dryRun = args.has')
    expect(generationScriptRaw).toContain('if (firstHash !== secondHash)')
    expect(generationScriptRaw).toContain('OpenAPI deterministic generation verified')
    expect(generationScriptRaw).toContain('OpenAPI snapshot hash mismatch')
    expect(generationScriptRaw).toContain('OpenAPI version mismatch')
    expect(generationScriptRaw).toContain('Contract version mismatch')
    expect(generationScriptRaw).toContain('OpenAPI coverage mismatch')
    expect(generationScriptRaw).toContain('openapi-typescript version mismatch')
    expect(generationScriptRaw).toContain("replace(/\\r\\n/gu, '\\n')")
    expect(gitAttributesRaw).toContain('contracts/openapi/eiams-v1.openapi.json text eol=lf')
  })
})
